#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 17 16:23:55 2019

@author: albertsmith
"""

rates=DR.rates(Type='R1',v0=[600,700,800,950])
rates.new_exp(Type='R2',v0=[600,700,800,950])
rates.new_exp(Type='NOE',v0=[600,700,800,950])

path2struct='/Users/albertsmith/Documents/github/pyDIFRATE/test_scripts/1d3z.pdb'

rates.molecule.load_struct(path2struct)
rates.molecule.select_atoms(sel1='name H')
rates.molecule.select_atoms(sel2='name N and not resname PRO and not resid 1')
rates.molecule.set_selection()


rates.new_mdl(Model='AnisoDif',tM=4.84e-9,xi=4,euler=[0,0,0])